name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy index.html to Nginx directory
        run: |
           cp *  /usr/local/var/www/
      - name: Restart Nginx
        run: |
          brew services restart nginx
