name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy index.html to Nginx directory
        run: |
          sudo cp *  /var/www/html/
      - name: Restart Nginx
        run: |
          sudo service nginx restart

      - name: Verify Nginx status
        run: |
          sudo service nginx status
